development:
  adapter: postgresql
  database: minibank_dev
  username: 'postgres'
  password: 'html5isgreat'
  host: localhost

test:
  adapter: postgresql
  database: minibank_test
  username: 'postgres'
  password: 'html5isgreat'
  host: localhost

production:
  adapter: postgresql
  database: minibank_prod
  username: 'postgres'
  password: 'html5isgreat'
  host: localhost


